name: backfill history (one-time)

on:
  workflow_dispatch:   # manual button

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install pandas yfinance requests
      - run: python backfill_history.py
      - run: |
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add history.csv
          git commit -m "backfill history" || echo "no changes"
          git push
