name: refresh gaming index   # appears in the Actions list

on:
  # ──────────────────── schedules ────────────────────
  schedule:
    # Hourly at 5 min past the hour  → intraday rows
    - cron:  '5 * * * *'
    # Daily at 00:05 UTC            → guarantees at least one row per date
    - cron:  '5 0 * * *'
  # Manual “Run workflow” button
  workflow_dispatch:

permissions:
  contents: write          # allow push back to the repo

concurrency:
  group: refresh-index     # never run two copies at the same time
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout repo
      - uses: actions/checkout@v4

      # 2 Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3 Install dependencies
      - name: Install libraries
        run: |
          pip install --upgrade pip
          pip install pandas yfinance requests openpyxl

      # 4 Run builder
      - name: Build latest snapshot & append history
        run: python build_index.py

      # 5 Commit generated files (only if they changed)
      - name: Commit and push
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add latest.json history.csv
          git diff --cached --quiet || git commit -m "auto: refresh index"
          git push
