name: refresh gaming index

on:
  # ❶ Schedule — runs at 5 minutes past every hour (UTC)
  schedule:
    - cron:  '5 * * * *'
  # ❷ Manual trigger button in the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest        # free hosted runner
    steps:
      - uses: actions/checkout@v4

      # Set up Python
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      # Install dependencies (only 3 small libs)
      - run: pip install yfinance pandas openpyxl

      # Run your builder
      - run: python build_index.py

      # Commit the generated files (latest.json, history.csv)
      - run: |add hourly workflow
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add latest.json history.csv
          git commit -m "auto: refresh index" || echo "no changes"
          git push
